### PR TITLE
Upgrade @actions/core to v1.10.0 to fix set-output deprecation

### PR DESCRIPTION
**Pull request by counterleft**
I didn't know how to test GH action after the package upgrade though. So, yikes?

References:
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- https://github.com/actions/toolkit/commit/b00a9fd033f4b30f2355acd212f531ecbbb9b38f

### CODE REVIEW

**Comment by cbrianhill** [comment]
I think we could test with a workflow that uses this.  You can specify a commit from the 'using' action [like this](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-a-commits-sha-for-release-management).  That way it can be tested pre-merge.

**Comment by counterleft** [comment]
Ah, nice. Then maybe the Dashboard Release Env workflow may be a good one. There's one deprecation warning there and it has a small footprint (`Release` env only).

**Comment by counterleft** [comment]
Ok, I have an test workflow-run using this branch and the deprecation output is now gone: https://github.com/daily-co/pluot-core/actions/runs/5524840025

I need to revert some debugging code from this branch and update the README. Then we should be good to merge.

Side note, it seems like workflows that use this create-tag-action no longer have to use the pattern of:

```yaml
- name: Checkout private GitHub Action
  uses: actions/checkout@v2
  with:
    repository: daily-co/create-tag-action
    token: ${{ secrets.SUBMODULES_GITHUB_PAT }}
    path: .github/actions/create-tag-action
- name: Tag the staging deployment
  uses: ./.github/actions/create-tag-action
  with:
    app-name: dashboard
    environment: staging
    github-token: ${{ secrets.GITHUB_TOKEN }}
```

But instead, our workflows can be shorten to:

```yaml
- name: Tag the release deployment
  uses: daily-co/create-tag-action
  with:
    app-name: dashboard
    environment: release
    github-token: ${{ secrets.GITHUB_TOKEN }}
```

This is because workflows can reference private actions that live inside another repo in the same org.

**Comment by counterleft** [comment]
There's two prettier/formatting commits in this PR along with the @actions/core upgrade. This explains the large +/- diff.

**Review by cbrianhill — APPROVED** [review]
Thanks for taking this on!  lgtm 🚀

**Pull request merged**
